config/routes.rb
Rails.application.routes.draw do

  # SDP: For consistency try and use a consistent approach, why do you have magazines here
  # when you have resources :magazines at the bottom?
  get 'magazines/index'

  # SDP: Usually the root path is placed at the bottom because the roots are processed
  root 'advertisements#index'
  devise_for :users

  # SDP: Aren't advertisements a nested resource of magazines, this is how you've modelled your application
  resources :advertisements
  resources :magazines
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  # SDP: Where is the belongs_to for magazines
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
	# SDP: Do not validate the foreign key, validate the publisher
	validates_presence_of :title, :publisher_id
	belongs_to :publisher
	has_many :advertisements

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	validates_presence_of :name
	has_many :magazines
	# SDP: Readup on validating associations to make this code a bit more durable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < SessionsController

before_action only: [:show, :edit, :update]

  def index
  	@advertisements = Advertisement.all
  end

  def show
  	@advertisement = Advertisement.find(params[:id])
  end

  def new
  	@advertisement = Advertisement.new
  end

  def create
    @advertisement = Advertisement.new(white_listed_parameters)
    if @advertisement.save
      flash[:notice] = 'New placement saved'
      redirect_to advertisements_path
    else
      render :new
    end
  end

  def edit
  	@advertisement = Advertisement.find(params[:id])
  end

  def update
  	@advertisement = Advertisement.find(params[:id])
  	if Advertisement.update(white_listed_parameters)
  		redirect_to advertisement_path(@advertisement)
  	else
  		render :edit
  	end
  end



  private

    def white_listed_parameters
    params
      .require(:advertisement)
      .permit(:format, :bleed_height, :bleed_width, :trim_height, :trim_width, :type_height, :type_width)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  def index
  	@magazines = Magazine.all
  end

  def show
    # SDP: What happens, if the user id cannot be found? Rails will raise an error which
    # can cause problems
  	@magazine = Magazine.find(params[:id])
  end

  def new
  	@magazine = Magazine.new
  end

  def create
    @magazine = Magazine.new(magazine_params)
    if @magazine.save
      flash[:notice] = 'New magazine added'
      redirect_to magazines_path
    else
      render :new
    end
  end

  private

    # SDP: Please check the format of your code, use a tool like Rubocop
    def magazine_params
    params
      .require(:magazine)
      .permit(:title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # SDP: If you are authenticated all the actions, then you can remove the only: for
  # brevity
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update]
end

app/helpers/advertisements_helper.rb
# SDP: Remove these if they are not used
module AdvertisementsHelper
end

app/helpers/application_helper.rb
# SDP: Remove this if they are not use
module ApplicationHelper
end

app/helpers/magazines_helper.rb
# SDP: Remove these if they are not used
module MagazinesHelper
end

app/views/advertisements/_form.html.erb
<%= form_for :advertisement, url: advertisements_path do |f| %>
  <p>
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </p>
 
  <p>
    <%= f.label :bleed_height %><br>
    <%= f.text_field :bleed_height %>
  </p>
 
  <p>
    <%= f.label :bleed_width %><br>
    <%= f.text_field :bleed_width %>
  </p>

  <p>
    <%= f.label :trim_height %><br>
    <%= f.text_field :trim_height %>
  </p>
 
  <p>
    <%= f.label :trim_width %><br>
    <%= f.text_field :trim_width %>
  </p>

  <p>
    <%= f.label :type_height %><br>
    <%= f.text_field :type_height %>
  </p>
 
  <p>
    <%= f.label :type_width %><br>
    <%= f.text_field :type_width %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/advertisements/edit.html.erb
<%= render 'form' %> 

app/views/advertisements/index.html.erb
<h1>Advertisements</h1>
<div>
  <table>
    <thead>
      <tr>
        <th>Format</th>
        <th>Bleed Height</th>
        <th>Bleed Width</th>
        <th>Trim Height</th>
        <th>Trim Width</th>
        <th>Type Height</th>
        <th>Type Width</th>
      </tr>
    </thead>
    <tbody>
      <% @advertisements.each do |advertisement| %>
        <tr>
          <td><%= link_to advertisement.format, advertisement_path(advertisement) %></td>
          <td><%= advertisement.bleed_height %></td>
          <td><%= advertisement.bleed_width %></td>
          <td><%= advertisement.trim_height %></td>
          <td><%= advertisement.trim_width %></td>
          <td><%= advertisement.type_height %></td>
          <td><%= advertisement.type_width %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <div> 
  <%= link_to 'Add New Placement', new_advertisement_path %>
  </div>

app/views/advertisements/new.html.erb
<%= render 'form' %> 

app/views/advertisements/show.html.erb
<h1><%= @advertisement.format %></h1>
  

<p><strong>Bleed</strong></p>
<p><%= @advertisement.bleed_height %> x <%= @advertisement.bleed_width %></p>

<p><strong>Trim</strong></p>
<p><%= @advertisement.trim_height %> x <%= @advertisement.trim_width %></p>

<p><strong>Type</strong></p>
<p><%= @advertisement.type_height %> x <%= @advertisement.type_width %></p>

<%= link_to 'Edit Placement', edit_advertisement_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpecsHelp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- SDP: Use a responsive framework, especially if HTML is not a strength -->
<%= yield %>

</body>
</html>

app/views/magazines/index.html.erb
  <% @magazines.each do |magazine| %>
    <tr>
      <p><%= magazine.title %></p>
    </tr>
  <% end %>

app/views/magazines/new.html.erb
<%= form_for :magazine, url: magazines_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

    <p>
    <%= f.submit %>
  </p>
<% end %>